// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('jei.hide.items', event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
	event.hide('kibe:drawbridge'),
	event.hide('kibe:regular_conveyor_belt'),
	event.hide('kibe:fast_conveyor_belt'),
	event.hide('kibe:express_conveyor_belt'),
	event.hide('kibe:wither_builder'),
	event.hide('kibe:cobblestone_generator_mk1'),
	event.hide('kibe:cobblestone_generator_mk2'),
	event.hide('kibe:cobblestone_generator_mk3'),
	event.hide('kibe:cobblestone_generator_mk4'),
	event.hide('kibe:cobblestone_generator_mk5'),
	event.hide('kibe:basalt_generator_mk1'),
	event.hide('kibe:basalt_generator_mk2'),
	event.hide('kibe:basalt_generator_mk3'),
	event.hide('kibe:basalt_generator_mk4'),
	event.hide('kibe:basalt_generator_mk5'),
	event.hide('kibe:xp_drain'),
	event.hide('kibe:xp_shower'),
	event.hide('kibe:magnet'),
	event.hide('kibe:glider_left_wing'),
	event.hide('kibe:glider_right_wing'),
	event.hide('kibe:white_glider'),
	event.hide('kibe:orange_glider'),
	event.hide('kibe:magenta_glider'),
	event.hide('kibe:pink_glider'),
	event.hide('kibe:light_blue_glider'),
	event.hide('kibe:yellow_glider'),
	event.hide('kibe:lime_glider'),
	event.hide('kibe:lime_glider'),
	event.hide('kibe:gray_glider'),
	event.hide('kibe:light_gray_glider'),
	event.hide('kibe:cyan_glider'),
	event.hide('kibe:blue_glider'),
	event.hide('kibe:purple_glider'),
	event.hide('kibe:green_glider'),
	event.hide('kibe:brown_glider'),
	event.hide('kibe:red_glider'),
	event.hide('kibe:black_glider'),
	event.hide('kibe:void_bucket'),
	event.hide('kibe:pocket_crafting_table'),
	event.hide('kibe:pocket_trash_can'),
	event.hide('kibe:entangled_bucket'),
	event.hide('kibe:entangled_bag'),
	event.hide('kibe:cooler'),
	event.hide('kibe:white_sleeping_bag'),
	event.hide('kibe:pink_sleeping_bag'),
	event.hide('kibe:orange_sleeping_bag'),
	event.hide('kibe:magenta_sleeping_bag'),
	event.hide('kibe:light_blue_sleeping_bag'),
	event.hide('kibe:yellow_sleeping_bag'),
	event.hide('kibe:lime_sleeping_bag'),
	event.hide('kibe:lime_sleeping_bag'),
	event.hide('kibe:gray_sleeping_bag'),
	event.hide('kibe:light_gray_sleeping_bag'),
	event.hide('kibe:cyan_sleeping_bag'),
	event.hide('kibe:sleeping_bag'),
	event.hide('kibe:purple_sleeping_bag'),
	event.hide('kibe:green_sleeping_bag'),
	event.hide('kibe:brown_sleeping_bag'),
	event.hide('kibe:red_sleeping_bag'),
	event.hide('kibe:black_sleeping_bag')
})