FlintlockDamage = 16
FlintlockReloadTime = 50
FlintlockQuickChargeTime = 5
FlintlockInaccuracy = 7.0
BlunderbussDamage = 4
BlunderbussReloadTime = 160
BlunderbussQuickChargeTime = 20
BlunderbussInaccuracy = 14.0
RifleDamage = 22
RifleReloadTime = 160
RifleQuickChargeTime = 20
RifleInaccuracy = 2.0
MusketDamage = 26
MusketReloadTime = 100
MusketQuickChargeTime = 10
MusketInaccuracy = 4.0
FlintlockCarbineDamage = 12
FlintlockCarbineReloadTime = 3
FlintlockCarbineQuickChargeTime = 1
FlintlockCarbineInaccuracy = 7.0
BlunderbehemothDamage = 4
BlunderbehemothReloadTime = 320
BlunderbehemothQuickChargeTime = 40
BlunderbehemothInaccuracy = 28.0
ResoluteRifleDamage = 22
ResoluteRifleReloadTime = 240
ResoluteRifleQuickChargeTime = 40
ResoluteRifleInaccuracy = 0.0
BoundlessMusketDamage = 318
BoundlessMusketReloadTime = 200
BoundlessMusketQuickChargeTime = 20
BoundlessMusketInaccuracy = 4.0
funMode = false
