generateOres = true
blacklistedOres = []
copperSurgenerationFactor = 4
spawnWithGuideBook = false
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
steamDrillFuelUseFactor = 5
steamDrillWaterUseFactor = 5
